### ISSUE TITLE
link checking path should be normalized

### ISSUE THREAD

**Issue by oupala** [davidxmoody/metalsmith-broken-link-checker#1]
I'm trying to use this plugin and I'm close to succeed.

> It checks for relative and root-relative links which do not have a corresponding file in the Metalsmith pipeline. It (currently) ignores all absolute links.
>
> Any broken links will cause an Error to be thrown (or a warning to be printed if options.warn is set). 

This works almost well. But it seems that the checked links have no normalized path. As a consequence, every link check fails even if the resource is really existing on the disk.

This makes impossible to use this plugin when developing on windows and integrating on linux.

Normalizing the path should make the plugin OS agnostic.

**Comment by davidxmoody** [comment]
Hi,

Thanks for reporting the issue.

I'm pretty sure I've fixed it. I now both convert from a Windows path to a unix one when computing the relative URI and then convert back to whatever the local filesystem path separator is before checking if the file exists in the metalsmith files object. 

I've released version 0.1.4 with the fix however I don't actually have a Windows machine to test it on :) Please could you let me know if it works and if it does then I will close the issue.

Thanks,
David

**Comment by oupala** [comment]
I can confirm that the new release is fixing the bug on my windows machine.

The plugin now works flawlessly.

**Comment by davidxmoody** [comment]
Glad it now works. I also see you have opened some other issues which I'll have a look at tomorrow.

Thanks for the feedback,
David
