### ISSUE TITLE
Add support to broken anchors

### ISSUE THREAD

**Issue by rbloch** [davidxmoody/metalsmith-broken-link-checker#15]
Hello,

I've been using this plugin in my metalsmith pipeline, however it only checks broken links and not for broken anchors. Will you add this feature any time soon?

I can also work on it and submit a pull request if you're available to review it and update your plugin. It's quite simple as it only requires to list all ids in the available files and to check for matches with the valid links hashes

What do you think about it?

**Comment by davidxmoody** [comment]
Hey, I just merged in your pull request and published version 1.0.0. Let me know if you have any problems with it.

**Comment by rbloch** [comment]
Hey,
Ok i will update our projects to use the new version and see if it works properly. Thanks for the merge.


Envoyé depuis mon smartphone Samsung Galaxy.
-------- Message d'origine --------De : David Moody <notifications@github.com> Date : 25.04.17  21:56  (GMT+01:00) À : davidxmoody/metalsmith-broken-link-checker <metalsmith-broken-link-checker@noreply.github.com> Cc : rbloch <remi.bloch@gmail.com>, Author <author@noreply.github.com> Objet : Re: [davidxmoody/metalsmith-broken-link-checker] Add support to broken anchors (#15) 
Hey, I just merged in your pull request and published version 1.0.0. Let me know if you have any problems with it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/davidxmoody/metalsmith-broken-link-checker","title":"davidxmoody/metalsmith-broken-link-checker","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/davidxmoody/metalsmith-broken-link-checker"}},"updates":{"snippets":[{"icon":"PERSON","message":"@davidxmoody in #15: Hey, I just merged in your pull request and published version 1.0.0. Let me know if you have any problems with it."}],"action":{"name":"View Issue","url":"https://github.com/davidxmoody/metalsmith-broken-link-checker/issues/15#issuecomment-297146449"}}}
