### ISSUE TITLE
on windows, the plugin fails to find existing ressources

### ISSUE THREAD

**Issue by oupala** [davidxmoody/metalsmith-broken-link-checker#6]
A strange bug appeared today on my console :

```
Warning: Link is broken: href: "/tags/architecture/", text: "architecture", in file: tags/soe/index.html
Warning: Link is broken: href: "/tags/soe/", text: "soe", in file: tags/soe/index.html
Warning: Link is broken: href: "/tags/engagement/", text: "engagement", in file: tags/soe/index.html
```

It appears that all links generated by the metalsmith-tags plugin generate a warning for metalsmith-broken-link-checker.

As you can see in the extract above, the plugin even fails to find the ressource where the link comes from !

Can the missing `/index.html` explain this behaviour ?

Could it be the last version of metalsmith-tags (recently updated to 0.11.0) ?

I'm stuck...

And the problem is not limited to the `tags/soe/index.html` file, all links to tags generate such warnings.

**Comment by davidxmoody** [comment]
This is weird I'll admit and I can't reproduce it. However I think it has something to do with Windows path separators again. My plugin splits the HTML link path by forward slashes and then re-joins them by the `path.sep` variable (which on Windows will be a backslash) before checking whether the file is in the `files` object. 

I had a look at the metalsmith-tags source code and it's generating filenames directly from the `path` and `pagePath` options without first normalizing them. In fact if you have a look at the filenames given in your snippet, they all have forward slashes and not backslashes. 

I guess we could change the metalsmith-tags plugin. Alternatively, because I feel like this same issue might come up again, I think I'm going to change my plugin so that it checks for either the forward slash version of the path or the backslash version existing before it throws an error. (Because, as far as I know, forward slash paths are still valid on Windows, right?)

**Comment by oupala** [comment]
I suppose that it has somethind to do with metalsmith-tags as all checked links are correct except those generated by metalsmith-tags.

It might also have something to do with Windows path separator if you can't succeed in reproducing the problem on linux. On what system are you trying to reproduce the problem ?

When I look at generated files and links, metalsmith-tags seems to work perfectly. Web link should **always** use `/` as a separator. I don't see why we should modify metalsmith-tags plugin. Are you talking about generated resources, or about metadata generated by metalsmith-tags ?

In fact, I think I don't know if metalsmith-broken-link-checker is working on real files, on only on metadata. Can you try to explain that a bit to me ?

**Comment by oupala** [comment]
[Debugging](https://github.com/mahnunchik/metalsmith-debug) on windows does not help much as I can only get the following output :+1: 

```
tags:
   { english: [ [Object], [Object], [Object], [Object] ],
     soe: [ [Object] ],
     ... }
```

**Comment by oupala** [comment]
I updated the issue as I tested my code in a linux box and I can't reproduce the problem either.

So it has definetly something to do with windows and linux path.

As I also updated metalsmith-tags recently, this could come from the metalsmith-tags update. But we need to get more informations and to understand better where is the failure before creating an issue on metalsmith-tags.

**Comment by davidxmoody** [comment]
I just published version 0.1.6 which I think should fix the problem. It now checks for filepaths of the format `path/to/file.html` as well as `path\to\file.html`. 

I think the second format is being natively generated by Metalsmith when it reads the files on Windows but the first format is being directly inserted into the files object by metalsmith-tags. Both forward and back slash relative paths are valid on Windows (I think) so they both get written to the filesystem. However my plugin was only checking for one kind. Now it checks for both.

Let me know if it works.

**Comment by oupala** [comment]
It works like a charm! I've also added some real broken links in order to check that all usecases are working well.

As you said, on windows the use of `/` or of `\` depends on the plugin, and (I also think that) both are valid on windows.

Here is an example of a log of a simple link generated by metalsmith : the file path uses `\`:

```
Warning: Link is broken: href: "broken", text: "real broken link", in file: about\index.html
```

Here is an example of a log of a link generated by metalsmith-tags : the file path use `\` but the link path uses `/`:

```
Warning: Link is broken: href: "/tags/multi word tag/", text: "multi word tag", in file: multi-word-tag\index.html
```

This last extract is a good illustration of the bug totocaster/metalsmith-tags#23 where the generated link is invalid and hence fail to be checked by metalsmith-broken-link-checker.

**Comment by davidxmoody** [comment]
I'm glad it works :)

Thanks for your help in raising/debugging it. I will now mark it as closed.
